version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "product"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: on-failure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4000
    volumes:
      - /app/node_modules
    expose:
      - 4000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  redis:
    image: redis
    command: ["redis-server", "--save 20 1", "--loglevel warning"]
    ports:
      - "6379:6379"

    

volumes: 
  data: