version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5430:5432"
    volumes: 
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    command: ["redis-server", "--save 20 1", "--loglevel warning"]
    ports:
      - "6379:6379"

volumes: 
  data: